[package]
name = "reccursive-cli"
description = "Command-line client for ReccursiveCommits"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "reccursive"
path = "src/main.rs"

[dependencies]
clap.workspace = true
reccursive-protocol = { path = "../protocol" }
reccursive-github = { path = "../github" }
serde.workspace = true
serde_json.workspace = true
tempfile = "3.0"
thiserror.workspace = true
uuid.workspace = true

[lints]
workspace = true
